receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: localhost:5317
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}/v1/metrics"
                headers:
                  - name: "authorization"
                    value: "${env:GRAFANA_CLOUD_BASIC_AUTH_HEADER}"
    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}/v1/logs"
                headers:
                  - name: "authorization"
                    value: "${env:GRAFANA_CLOUD_BASIC_AUTH_HEADER}"
